global:
  scrape_interval:     15s 
  
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'movimento-api'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
        - targets: ['10.0.0.169:8000']    