spring:
  datasource:
    url: jdbc:mysql://${MYSQL_URL:localhost:3306}/movimento_api?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useTimezone=true&serverTimezone=America/Sao_Paulo
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

server:
  port: 8000


