{
 "title": "Estatiticas Da Api de Movimentos",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Inclusão de Movimentos",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"movimento-api\", method=\"POST\",uri=\"/api/movimento\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    }
   ]
  },
  {
   "title": "Consulta De Movimentos",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"movimento-api\", method=\"GET\", uri=\"/api/movimento/{id}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    }
   ]
  },
  {
   "title": "Atualização de Movimentos",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"movimento-api\", method=\"PUT\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    }
   ]
  },
  {
   "title": "Deleção de Movimentos",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\r\nhttp_server_requests_seconds_count{job=\"movimento-api\", method=\"DELETE\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    }
   ]
  },
  {
   "title": "Time de Resposta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{job=\"movimento-api\", method=\"POST\",uri=\"/api/movimento\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_max{job=\"movimento-api\", method=\"GET\",uri=\"/api/movimento/{id}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_max{job=\"movimento-api\", method=\"PUT\",uri=\"/api/movimento/{id}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_max{job=\"movimento-api\", method=\"DELETE\",uri=\"/api/movimento/{id}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    }
   ]
  }
 ]
}